### ISSUE TITLE
Extending a factory with new fields

### ISSUE THREAD

**Issue by Ragura** [thoughtbot/fishery#107]
**Is your feature request related to a problem? Please describe.**
First of all, I love this project! You say it was built with Factoy Boy as an inspiration, but I work with Factory Boy on a regular basis in a Django project and Fishery is SO much easier to work with. Not to mention the full typescript support that just makes it a joy to use. I've only got one issue I can't figure out if it's possible or not with the current toolset. 
In our production project we have various different types of nodes, which are represented as data objects. Each of these nodes have some common fields and a few specific fields. I'm trying to figure out if I can build a standard, common Node factory and then define separate factories for each node with the common core as a shared fieldset.
For example:
```
const coreFactory = Factory.define<Core>(() => {
  return {
    field1: 'this',
    field2: 'that',
})

const specificFactory = Factory.define<Specific>(() => {
  return {
     ...fieldsOfCoreFactory,
     field3: 'more',
     field4: 'and more',
  }
}
```

**Describe the solution you'd like**
I love the way `params` and `transientParams` work, but as far as I can tell they don't allow me to define new return fields. I also don't know if extending the factory class could do what I need it to do. It would be great if there was a way to extend the returned object from the Factory without resorting to tricks such as deep cloning shared objects into the return field. Perhaps an `.extend()` method to do just that, like how you can use `.params()` to create new outcomes based on existing fields?

**Describe alternatives you've considered**
I've thought about merging return objects by deep cloning, but it requires creating separate objects outside of factories just for this reason. It also seems to mess with the types if I do that, though that could just have been me.

Again, thank you for building this awesome package! I've read it is a side project for you, so it's understandable if my request isn't in the cards right now. If you know of another workaround in the meanwhile, I'm open to that too!

**Comment by jagers** [comment]
I ran into this same use case!

What I've decided to do, for now, is build a Core object inside of the Specific factory

```
const coreFactory = Factory.define<Core>(() => {
  return {
    field1: 'this',
    field2: 'that',
})

const specificFactory = Factory.define<Specific>(({ params }) => {
  const fieldsOfCoreFactory = coreFactory.build(params)
  return {
     ...fieldsOfCoreFactory,
     field3: 'more',
     field4: 'and more',
  }
}
```

I've just started using this approach so I'm not sure if it'll run into any issues

**Comment by stevehanson** [comment]
Thank you for opening this issue. I also recommend the approach @jagers mentioned. Factories can use other factories internally. 

For more complicated scenarios, like if the `core` params don't overlap exactly with the `specific` factory params (eg. if core params nested or in an array, etc), you can also leverage [`traits`](https://github.com/thoughtbot/fishery#adding-reusable-builders-traits-to-factories) in your `specificFactory` that can help provide an interface for supplying the core properties, like `specificFactory.withCoreParams(myCoreParams).build()`.

I'm going to close this since we've discussed some workarounds.
