### ISSUE TITLE
Factory cannot build class with methods

### ISSUE THREAD

**Issue by gerggggggg** [thoughtbot/fishery#121]
**Description**

Many of my classes have methods in them, not just properties.  It seems that the documentation for Fishery does not say anything about building Factories for classes with methods and in general, it seems that this just does not work.

**To Reproduce**

```typescript
import { Factory } from "fishery";

class Thingy {
  foo: string;
  bar: number;

  constructor(foo: string, bar: number) {
      this.foo = foo;
      this.bar = bar;
  }

  to_string(): string {
      return `${this.foo}: ${this.bar}`;
  }
}

const thingyFactory = Factory.define<Thingy>(() => ({
  foo: 'frog',
  bar: 7
}));
```
Produces the following error when trying to use `thingyFactory`:

`Property 'to_string' is missing in type '{ foo: string; bar: number; }' but required in type 'Thingy'.typescript(2741)`

Are classes with methods not supported?

**Comment by stevehanson** [comment]
Hi, you can set up your factory to return your custom class. Fishery provides little "magic". It will use whatever is returned by your factory as the return object when you call `build`. After getting the object from the factory, Fishery layers in any passed params using `Object.assign`, which works fine with classes. Here is a [code sandbox demonstrating this](https://codesandbox.io/p/devbox/white-snow-gd3tcq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpivgs2n00073b6ky50pxr6j%2522%252C%2522sizes%2522%253A%255B51.96517412935323%252C48.03482587064677%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpivgs2n00033b6kau82x1kg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpivgs2n00053b6k0lndsvv8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpivgs2n00063b6kmwel7egv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpivgs2n00033b6kau82x1kg%2522%253A%257B%2522id%2522%253A%2522clpivgs2n00033b6kau82x1kg%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpivgs2n00063b6kmwel7egv%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpivgs2n00063b6kmwel7egv%2522%257D%252C%2522clpivgs2n00053b6k0lndsvv8%2522%253A%257B%2522id%2522%253A%2522clpivgs2n00053b6k0lndsvv8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpivgs2n00043b6kmvk4jv5z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clpivjkxc00pb3b6khdyuvh6o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clpivjl2o015yeeg66wkxduet%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpivjkxc00pb3b6khdyuvh6o%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) with your example. And the code inline for reference:

```ts
import { Factory } from "fishery";
class Thingy {
  foo: string;
  bar: number;

  constructor(foo: string, bar: number) {
    this.foo = foo;
    this.bar = bar;
  }

  hello(): string {
    return `Hello ${this.foo}`;
  }
}

test("this works", () => {
  const userFactory = Factory.define<Thingy>(() => {
    return new Thingy("frog", 7);
  });

  expect(userFactory.build().foo).toEqual("frog");
  expect(userFactory.build({ foo: "dog" }).foo).toEqual("dog");
  expect(userFactory.build().hello()).toEqual("Hello frog");
});
```

I'm going to close this issue, but feel free to open it if needed.

**Comment by gerggggggg** [comment]
Thank you for the help, this indeed did what I needed.
