### ISSUE TITLE
Support for flow types

### ISSUE THREAD

**Issue by rakeshpetit** [thoughtbot/fishery#15]
We observed that the library is not able access flow types. Is that something known and you have plans to add it at some point later or would it only support TypeScript ? Would be happy to pair if it works and needs some configuration in the project.

**Comment by stevehanson** [comment]
I don't know have much experience with Flow, but if someone in the community were interested in adding Flow types to the project in an unobtrusive way, I'd support that!

**Comment by stevehanson** [comment]
I'm going to close this. If anyone wants to figure this out, feel free to submit a PR.
