### ISSUE TITLE
Async Support

### ISSUE THREAD

**Issue by casey-chow** [thoughtbot/fishery#16]
I'm trying to integrate this library with TypeORM, and I'd like to make factories as follows:

```ts
export const userFactory = Factory.define<User, Factories>(({ afterCreate }) => {
  afterCreate(async (user) => {
    return await manager.save(user);
  });

  const user = getRepository(User).create({
    username: randomString(),
  });

  return user;
});
```

However, `afterCreate` [does not support asynchronous callbacks](https://github.com/thoughtbot/fishery/blob/master/lib/builder.ts#L51-L59), which means that client code needs to save after building. It would be great to be able to handle saving in the factory like in factory_bot!

**Comment by stevehanson** [comment]
Thanks for reporting this, @casey-chow. This seems like something that could make sense to support. I've made a note to take a look at this on Friday when I should have some time, or if you want to take a look, feel free and we could discuss approaches in this issue thread.

**Comment by casey-chow** [comment]
Yeah, sure thing. My initial thinking, after posting the above code sample, was to follow this code pattern:

```ts
const userFactory = Factory.define<User, Factories>(({ toSave }) => {
  // toSave passes in the built user and expects a promise of the user, as saved
  toSave(async (user) => {
    return await getRepository(User).save(user);
  });

  return {
    username: randomString(),
  };
});

// create returns a promise of the user, as saved
const user = await userFactory.create();
```

I realized that overloading `afterCreate` wouldn't work because `Factory#build` already does not return a promise. What do you think?

**Comment by stevehanson** [comment]
This overall approach seems great at first look. I like the idea and naming of `create` being asynchronous and `build` being synchronous.

I'm not sure yet on the naming of `toSave`. Ideally it would map somewhat to `create` to make it clear that it's triggered when `create` is called. Some alternatives that come to mind are `onCreate` or just `create`, but I'll think some more on that. 

Another thing to consider is what the implications for `afterCreate` will be. Currently, that is called after an object is built, but adding `onCreate` could introduce confusion since that is only called on `create`. One solution would be to only call `afterCreate` after `create` is called, and we could introduce an `afterBuild` that is called every time an object is built (same functionality as existing `afterCreate`). This would be a backwards-incompatible change, though it wouldn't bother me too much since we're still 1.0.

Thanks again. I'll think about this more and provide some more thoughts on Friday.

**Comment by stevehanson** [comment]
@casey-chow I've started working on this and have `create` and `createList` working. 

I went with calling the `toSave` method `onCreate` for now and renamed `afterCreate` to `afterBuild`.

I'm still thinking through things and will try out TypeORM and probably a back-end ORM like Seqelize to test some things out before merging anything in.

I'm also interested in exploring a way to define a global `onCreate`, maybe when calling `register`, so that we don't have to provide the creation logic in each factory.

Here's what I have so far if you wanted to take a look and try it out: https://github.com/thoughtbot/fishery/compare/async

**Comment by casey-chow** [comment]
Awesome, thanks for keeping me in the loop! I did a quick survey of some other JS-based ORMs (Bookshelf, Objection, Mongoose) and it seems like this model should work for all for persisting all of them.

> One solution would be to only call afterCreate after create is called, and we could introduce an afterBuild that is called every time an object is built (same functionality as existing afterCreate). This would be a backwards-incompatible change, though it wouldn't bother me too much since we're still 1.0.

If you're okay with the backwards-incompatibility, it definitely makes a lot of sense since it keeps naming consistent with factory_bot. I think the other option is to keep `afterCreate` and make the following step `toPersist`/`afterPersist` perhaps?

**Comment by ObliviousHarmony** [comment]
Hey there! First of all, thanks for creating this! I'm currently looking into using this library for generating models via REST for end-to-end tests, and I've got to say, I'm a really big fan of these changes! This new `create` method allows us to generate the model on the server and then return it to the client, so this is really great. (createList/buildList might need optimized for bulk generation, but this is a great place to start!)

Do you know when you might be merging them into master and cutting a new release?

**Comment by stevehanson** [comment]
@ObliviousHarmony thanks for the feedback! And great points with `createList` needing to potentially be optimized. I'm going to try to take a look at this more in the next week or so. I'd really like to get this out there. 

One holdup for me, besides just being busy, is I'd like to determine if we need a global save "adapter" as opposed to defining the `onCreate` logic in each factory. If we went the adapter route, then it seems possible there could be community adapters for various back-ends or use-cases. We might need the `onCreate` regardless, in which case we could just ship without the adapter bit. I'd be interested in any thoughts you or anyone else has around this.

I'm going to think more on this in the next week or so and try to recruit some more help, as it's mostly just been me maintaining this library so far.

**Comment by ObliviousHarmony** [comment]
@stevehanson I think there's a good case here for moving the async work into adapters. One of the use-cases I had in mind was using the database directly for high-volume generation of data, but the current `onCreate` solution would require a separate factory altogether. I'm not sure that the `onCreate` is needed in this scenario, as the strange edge-cases that may require something after the adapter seems like something a package consumer should handle.

Here's something I put together showing what I'm thinking about; I also changed the `createList` function to allow for adapters to optimize the bulk saving. Let me know if I should submit a pull request!

https://github.com/thoughtbot/fishery/compare/async...ObliviousHarmony:async-adapters

**Comment by ObliviousHarmony** [comment]
@stevehanson Howdy! Have you had any time to consider this further?

**Comment by ObliviousHarmony** [comment]
I've looked over what I did two weeks ago and I see some clear places for improvement. The Adapter API should be consistent with the Factory API so that consumers don't have to create classes for every adapter they want. I'm also not entirely happy with the way that adapters are assigned to factories. 

I've also been watching the work on #18 and I think being able to change the adapter in a trait could be very useful as well. I'd definitely like to take another pass at this, so please share any ideas you have :)

**Comment by stevehanson** [comment]
@ObliviousHarmony I haven't yet, but I've also been keeping this in mind as I've worked on #18. 

After #18, we will likely begin utilizing inheritance a little more, so we could potentially implement adapters by creating a top level factory and then inheriting from it for all other factories. Here's some rough code that I just typed up quickly illustrating the idea:

```typescript
class ApplicationFactory<T> extends Factory<T> {
  private factoryClass: any;

  // not sure at all if this mechanism will exist or what it would look like
  onCreate(object) {
    if(!this.factoryClass) { throw new Error('factory class not defined, call `for` first') }

    return this.factoryClass.create(object);
  }

  for(factoryClass: T) {
   this.factoryClass = factoryClass;
  }
}

class UserFactory extends ApplicationFactory<User> {}
const userFactory = UserFactory.define(() => ({ ... }).for(User)
```

I really haven't thought about this much yet, so I'm not sure if it will end up as the solution, but it seems promising.

**Comment by ObliviousHarmony** [comment]
@stevehanson I've been thinking this over and I like it quite a bit. Using inheritance here will provide an opportunity for consumers to implement asynchronous handling however they like, without being tied to any specific API. I think a good way to implement this would be to leave the `FactoryBuilder` alone and keep all of the async functionality in a new `AsyncFactory` class. Something like this might be nice:

```typescript
class AsyncFactory<T, F = any, I = any> {
    private creator: CreatorFn<T>;

    static define<T, F = any, I = any>(
        generator: GeneratorFn<T, F, I>,
        creator: CreatorFn<T>
    ) {
        let factory = new Factory<T, F, I>(generator);
        factory.creator = creator;
        return factory;
    }

    create(
        params: DeepPartial<T> = {}, 
        options: BuildOptions<T, I> = {}
    ): Promise<T> {
        let model = this.build(params, options);
        return this.creator(model, options);
    }

    createList(
        num: number,
        params: DeepPartia,T> = {},
        options: BuildOptions<T, I> = {}
    ): Promise<T[]> {
        let promises: Promise<T>[] = [];
        for (let i = 0; i < number; i++) {
          promises.push(this.create(params, options));
        }

        return Promise.all(promises);
    }
}

AsyncFactory.define<User, Factories, UserTransientParams>(
  () => {...},
  (model, options) => {
      return api.create(model);
  }
  },
);

```

**Comment by stevehanson** [comment]
I've published the traits and factory extension API changes [from this PR](https://github.com/thoughtbot/fishery/pull/20) as v0.4.0. With those changes, it's now possible to add your own mechanism for async factories as illustrated in the last couple comments. I will still be working on this soon but will be prioritizing some other roadmap items first. I do have some time this week, so it's still possible I will get to it this week.

**Comment by uchagani** [comment]
@stevehanson is it possible to get an example of how you envision an async factory being implemented with the changes from #20 ?  Thank you.

**Comment by matdehaast** [comment]
@stevehanson any news on the async support? Can I help in any way to get it done?

**Comment by datner** [comment]
won't this work?
```ts
export const userFactory = Factory.define<User, Factories>(({ afterCreate }) => {
  afterCreate((user) => {
    async function save() {
      await manager.save(user);
    }
    save()
  });

  const user = getRepository(User).create({
    username: randomString(),
  });

  return user;
});```
also why even await it at all I don't understand.. it's not like you need the return value from `manager.save`

```ts
export const userFactory = Factory.define<User, Factories>(({ afterCreate }) => {
  afterCreate((user) => {
     manager.save(user);
  });

  const user = getRepository(User).create({
    username: randomString(),
  });

  return user;
});```

**Comment by casey-chow** [comment]
@datner The return value from `manager.save` is valuable because I need to grab the primary key, which is database-generated, as well as other database-generated default values, such as creation timestamps, etc. This ensures that the database is generating these values in the formats I expect.

**Comment by datner** [comment]
It's this for a test or a seed? Either way it sounds like you don't really need to use this hook..

```ts
const user = userFactory.build({...})
const dbUser = manager.save(user)
```
This would also be preferable since the factory shouldn't cause side-effects. If this feels dirty for some reason, you can wrap all that in a repository
