### ISSUE TITLE
Using one property's value in another

### ISSUE THREAD

**Issue by uchagani** [thoughtbot/fishery#24]
Given the factory:

```typescript
export default Factory.define<User>(() => ({
  firstName: 'John',
  lastName: 'Smith',
  fullName: `${firstName} ${lastName}`
}));
```

How can I use `firstName` and `lastName` to form the value for `fullName` dynamically?

**Comment by uchagani** [comment]
I know I can use `afterCreate`/`afterBuild` but was wondering if there is a way to do it without them

**Comment by stevehanson** [comment]
What you want is `params`:

```typescript
export default Factory.define<User>(({ params }) => {
  const {
    firstName = 'John',
    lastName = 'Smith',
  } = params;
  const fullName = `${firstName} ${lastName}`;

  return {
    firstName,
    lastName,
    fullName,
  }
})
```

There's a similar example [in the readme](https://github.com/thoughtbot/fishery#use-params-to-access-passed-in-properties).
