### ISSUE TITLE
How do I call an API in a factory definition?

### ISSUE THREAD

**Issue by uchagani** [thoughtbot/fishery#26]
One of my properties depends on fetching a value from an API.  How can that be accomplished?

**Comment by stevehanson** [comment]
`facotry.build()` is not asynchronous, so there is not a way to achieve this currently out of the box. We are working on adding an asynchronous `create` method in #16 which could work for your situation once we finish implementing it.

**Comment by stevehanson** [comment]
I'm going to close this as a duplicate of #16.
