### ISSUE TITLE
Sequence start at 0...

### ISSUE THREAD

**Issue by anlek** [thoughtbot/fishery#27]
Starting to use Fishery recently and noticed an unexpected behaviour. The sequence that factories start with is `0`, however, `FactoryBot`'s sequences start with `1`. I believe 1 is a better choice, as all of our Fishery's factories have to do:
```js
export default Factory.define(({ sequence }) => ({
  id: sequence + 1,
  // other attributes set here...
}))
```

Let me know if I'm missing something.

**Comment by stevehanson** [comment]
Thanks, @anlek. This behavior was just changed in #19 so 1 is the starting value. I'll make a new release with this soon.
