### ISSUE TITLE
Overwriting params whose values are arrays

### ISSUE THREAD

**Issue by apalmer0** [thoughtbot/fishery#33]
I've got an object whose interface looks like this:

```js
interface IPallet {
  id: number
  pictures: IPicture[]
}
```

and I've created a factory like this:

```js
import { Factory } from 'fishery'
import { IPallet, IPicture }  from '../types'

export default Factory.define<IPallet>(({ params, sequence }) => ({
  id: sequence,
  pictures: (params.pictures as IPicture[]) || [{ uri: 'abc123' }],
}))
```

the type coercion happening in `pictures` (`params.pictures as IPicture[]`) is something else I don't understand, but my main question is about overwriting params whose values are arrays; it seems I'm not able to overwrite the default `pictures` value as I expected I'd be able to, namely:

```js
import palletFactory from '../factories/pallet'
...
const pallet = palletFactory.build({ pictures: [] })
```

using this, the `pictures` attribute of `pallet` would still be `[{ uri: 'abc123' }]`.

Unless I'm doing something wrong, the only way I can successfully do this is by using associations.

Questions:
1) am I doing something wrong? Happy to provide more detail if this isn't sufficient.
2) is there some convention being applied to attributes whose values are arrays that forces them to be associations? Or is that a side effect of something else?

I think the readme could be updated to address this - I'd be happy to do that once I understand what's going on here!

**Comment by stevehanson** [comment]
@apalmer0 there is no convention applied to arrays, and you can definitely use the approach you are trying. 

I noticed when you build your object, you are passing `pallets: []`, but your factory looks at `params.pictures`. You would need to either pass `pictures: []` when you build your object or update your factory to access `params.pallets`. Let me know if that helps!

**Comment by apalmer0** [comment]
> @apalmer0 there is no convention applied to arrays, and you can definitely use the approach you are trying.
> 
> I noticed when you build your object, you are passing `pallets: []`, but your factory looks at `params.pictures`. You would need to either pass `pictures: []` when you build your object or update your factory to access `params.pallets`. Let me know if that helps!

Ugh shoot, sorry - that's a typo, I actually am passing `{ pictures: [] }`. That's embarrassing. I'm going to edit my question to reflect that.

Thanks for the quick response! Let me go back to my setup and see if I'm doing anything else differently before taking any more of your time.

**Comment by stevehanson** [comment]
No worries! I did just try out your example, and it worked for me if that helps. Don't hesitate to reach out if it's still not working for you. Here was the test I used:

```typescript
interface IPicture {
  uri: string;
}

interface IPallet {
  id: number;
  pictures: IPicture[];
}

const factory = Factory.define<IPallet>(({ params, sequence }) => ({
  id: sequence,
  pictures: (params.pictures as IPicture[]) || [{ uri: 'abc123' }],
}));

expect(factory.build({ pictures: [] }).pictures).toEqual([]);
expect(factory.build().pictures).toEqual([{ uri: 'abc123' }]);
```

**Comment by apalmer0** [comment]
> No worries! I did just try out your example, and it worked for me if that helps. Don't hesitate to reach out if it's still not working for you. Here was the test I used:
> 
> ```ts
> interface IPicture {
>   uri: string;
> }
> 
> interface IPallet {
>   id: number;
>   pictures: IPicture[];
> }
> 
> const factory = Factory.define<IPallet>(({ params, sequence }) => ({
>   id: sequence,
>   pictures: (params.pictures as IPicture[]) || [{ uri: 'abc123' }],
> }));
> 
> expect(factory.build({ pictures: [] }).pictures).toEqual([]);
> expect(factory.build().pictures).toEqual([{ uri: 'abc123' }]);
> ```

Cool, thanks! That settles that then, I'll go back to the drawing board and figure out what I was doing wrong. I'll update here once I know more.

**Comment by stevehanson** [comment]
@apalmer0 another similar issue, #36, was just opened, so I will be looking into this. Thanks again for reporting. Any further discussion will be in that issue thread, so feel free to follow along there.

**Comment by stevehanson** [comment]
It does look like #36 is slightly different, since their factory doesn't utilize `params` like yours does. Your scenario still passes tests for me.
