### ISSUE TITLE
DeepPartial doens't partial nested arrays

### ISSUE THREAD

**Issue by datner** [thoughtbot/fishery#52]
repl [here](https://repl.it/talk/share/DeepPartial-error/125220)

having an object with a collection inside it doesn't work

```ts
// each fish has 10 keys ( name, age, favorite food, whatever)
const collectionFactory  = Factory.define({
  fish: [{...}]
})

// breaks
cost foo = collectionFactory.build({ fish: [ {name: 'jeff'}])
```

even if you account for it, it still breaks:
```ts
interface Fish {
  name: string
  fins: number
  hasChildren: boolean
}

interface School {
  fishType: string
  members: Fish[]
}

const fishFactory = Factory.define<Fish>(() => ({
  name: 'jacob',
  fins: 2,
  hasChildren: false
}))

const schoolFactory = Factory.define<School>(({params}) => ({
  fishType: 'makrel',
  // note this
  members: params.members ? params.members.map(m => fishFactory.build(m)) : fishFactory.buildList(1)
}))

const school = schoolFactory.build({ members: [{name: 'meg'}) // TypeError: {name: string} is not assignable to Fish, missing fins, hasChildren
```

>just write `schoolFactory.build({member: fishFactory.buildList(1, {name: 'meg'})`

sure, but that is missing the point. I might not want to expose a factory for fish because it doesn't make sense and requires familiarity with it to use.

maybe something like this would work?

```ts
const factory = Factory.define(({list}) => ({
   list: list({ name: 'jacob', fins:2, hasChildren: false})
}))
```

**Comment by stevehanson** [comment]
Hi, @datner. I see what you're trying to do, and I understand why it is frustrating that you aren't able to pass a partial of your association collection directly in `build`. The reason this doesn't work is that the TypeScript types don't have a way to guarantee you are going to actually create the `members` from the partial members. There isn't a clear way to me on how I could make that type-safe.

I think you will want to either use [transient params](https://github.com/thoughtbot/fishery#params-that-dont-map-to-the-result-object-transient-params) or [factory builders / traits](https://github.com/thoughtbot/fishery#adding-reusable-builders-traits-to-factories) to accomplish this.

### Traits

I think this is the simplest approach. The idea is you define a custom method on your factory for building the members:

```
class SchoolFactory extends Factory<School> {
  withMembers(members: Partial<Fish>[]) {
    return this.params({ members: members.map(m => fishFactory.build(m)) });
  }
}

const schoolFactory = SchoolFactory.define(({params }) => {
  return {
    fishType: 'makrel',
    members: []
  }
})

const school = schoolFactory.build().withMembers([{ name: 'meg' }])
```

### Transient params

The other approach is using transient params. It's a little clunkier to use, in my opinion.

```typescript
type TransientParams = {
  members: Partial<Fish>[];
}

const schoolFactory = Factory.define<School, TransientParams>(({params, transient }) => {
  const members = transient.members ? params.members.map(m => fishFactory.build(m)) : params.members || fishFactory.buildList(1));

  return {
    fishType: 'makrel',
    members
  }
})

const school = schoolFactory.build({}, { transient: { members: [{name: 'meg'}] })
// or:
const school = schoolFactory.build().transient({ members: [{name: 'meg'}] })
```

Hope that is helpful. I realize this is a few months old and that you might have moved on by now.
