### ISSUE TITLE
Cannot find module './factories' or its corresponding type declarations.

### ISSUE THREAD

**Issue by humbienri** [thoughtbot/fishery#82]
Hello,

I'm trying to follow your documentation but struggling. Am new to JS/TS and of course to Fishery as well.

Am getting the above error on the import line:
`import {factories} from './factories';`

Is there some other file I need to drop in the factories folder? Please.

Thank you for your time.

**Comment by humbienri** [comment]
Any thoughts on this? Please.

I am new to JS/TS so could this be related to my repo being a JS repo and I just don't have the right Typescript "stuff" installed or a tsconfig.json file?

In advance, thank you.

**Comment by stevehanson** [comment]
Hi, thanks for opening this issue. In this case, I think the documentation is just a little confusing. It assumes you've set up your factories in a file called `factories.js` or `factories/index.js` that looks something like this:

```js
// factories.js

const factory1 = Factory.define(...);
const factory2 = Factory.define(...);
export const factories = { factory1, factory2 };
```

You can set up your factories however you please, though, so this setup is not strictly necessary. I hope that helps. Let me know if you still run into any issues. I will leave this issue open for a little while longer. I will also make a note to update the readme.

**Comment by humbienri** [comment]
Thank you very much @stevehanson! I'll give that a go and report back. Fishery is looking very promising so we'd love to crack this nut.

Any gotchas with regards to using this with Typescript?

Cheers!

**Comment by stevehanson** [comment]
@humbienri sounds good. It’s designed to work with TypeScript, so you should be good to go. Have a nice weekend.

**Comment by humbienri** [comment]
I got this to work. Somewhat! But I'll open another ticket for that once I search on here to see if others have had this issue: generating an array/list of objects.

Thank you very much Steve!
