### ISSUE TITLE
How to use onCreate

### ISSUE THREAD

**Issue by humbienri** [thoughtbot/fishery#87]
Hello again,

Can you explain a bit more about how to use onCreate hook. It seems the docs assume familiarity or previous hands on experience with Factory Bot? Which I don't have.

Fishery doesn't, out-of-the-box, actually create a record in the database right? That would be something extra that would have to be hand coded? The documentation I've read on Ruby's Factory Bot just says that the model/record gets created in the database if one uses `create` vs. `build`.

So, for example, for Fishery I would have to somehow stitch up usage of `axios`, for example, to make an API call to create some record and then wire up that API call to Fishery's `Create/onCreate` methods?

Or am I way off here? Again, thank you very much for any assistance you can grant.

**Comment by stevehanson** [comment]
Hi, you are correct that, unlike FactoryBot which saves to a database on `create`, Fishery doesn't do anything on create by default. You have to define an `onCreate` method with your factory as described [in the readme](https://github.com/thoughtbot/fishery#on-create-hook). The `onCreate` method can do whatever you'd like it to as long as it returns a promise with the object -- eg. manually use axios or other library to make a network call, etc. You would also be responsible for cleaning up your database or whatever external service you're calling if applicable.

Let me know if you still have any questions.

**Comment by humbienri** [comment]
That sucks! Awesome that you replied though. Thank you Steve!

This is hurting my brain. :)
